'⚡ command':
  - '### What part of PanAdmin is this related to\?\s+Command'
'📱 UI':
  - '### What part of PanAdmin is this related to\?\s+User Interface'
'📄 documentation':
  - '### What part of PanAdmin is this related to\?\s+Documentation'
'🛡️ anti-exploit':
  - '### What part of PanAdmin is this related to\?\s+Anti-Exploit'
'github':
  - '### What part of PanAdmin is this related to\?\s+GitHub Repository'
'🖇️ loader':
  - '### What part of PanAdmin is this related to\?\s+Loader/Settings'
'🎏 miscellaneous':
  - '### What part of PanAdmin is this related to\?\s+Other'
